version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: book-store
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book-store
    volumes:
      - book-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - book-network

volumes:
  book-data:

networks:
  book-network: